default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shop_development
  username: kopilka_rec
  password: dkvs43gh4
  host: localhost
  port: 5432

test:
  <<: *default
  database: shop_test
  port: 5432

production:
  <<: *default
  database: chats_production
  username: chats
  password: <%= ENV['CHATS_DATABASE_PASSWORD'] %>
